version: "3"
services:
  main:
    build: ./docker
    container_name: research-web-accessibility
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - 8889:8889
    command: jupyter notebook --ip=0.0.0.0 --port 8889 --allow-root --no-browser
